name: AWS OIDC Authentication

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC Token (for troubleshooting)
        run: |
          echo "OIDC Token Contents:"
          curl -sLS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' | cut -d'.' -f2 | base64 -d | jq
          echo "Using Role ARN: arn:aws:iam::878582761299:role/github-actions"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::878582761299:role/github-actions
          aws-region: us-west-2
          role-session-name: github-oidc-${{ github.run_id }}
          mask-aws-account-id: false  # Helps with debugging

      - name: Verify AWS access
        run: |
          echo "Caller Identity:"
          aws sts get-caller-identity
          echo "S3 Buckets:"
          aws s3 ls
